# Generated by Django 5.2.6 on 2025-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel', 'Подорож'), ('adventure', 'Пригода')], max_length=50),
        ),
    ]
